openapi: 3.0.3
info:
  title: Family Care Network API
  version: 0.1.0
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200': { description: OK }
  /auth/request-otp:
    post:
      summary: Request OTP via SMS or Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneE164: { type: string }
                email: { type: string, format: email }
                purpose: { type: string, enum: [login, verify_phone, verify_email] }
      responses:
        '200': { description: OTP dispatched }
  /auth/verify-otp:
    post:
      summary: Verify OTP and login/signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneE164: { type: string }
                email: { type: string, format: email }
                code: { type: string }
                role: { type: string, enum: [FAMILY, CAREGIVER, ADMIN] }
      responses:
        '200':
          description: JWT token and user
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      role: { type: string }
                      email: { type: string }
                      phoneE164: { type: string }
  /me:
    get:
      summary: Get current user with profile
      security: [ { bearerAuth: [] } ]
      responses:
        '200': { description: User object }
  /me/family:
    put:
      summary: Create/update family profile and members
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName: { type: string }
                address: { type: string }
                city: { type: string }
                preferredLanguage: { type: string }
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      fullName: { type: string }
                      relation: { type: string }
                      birthDate: { type: string }
                      notes: { type: string }
      responses:
        '200': { description: Family profile }
  /me/caregiver:
    put:
      summary: Create/update caregiver profile
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName: { type: string }
                gender: { type: string }
                languages: { type: array, items: { type: string } }
                specialties: { type: array, items: { type: string } }
                certifications: { type: array, items: { type: string } }
                hourlyRateEgp: { type: integer }
                bio: { type: string }
                city: { type: string }
                availabilityJson: { type: string }
      responses:
        '200': { description: Caregiver profile }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT